/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sudoku;

import java.awt.Color;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author raymondbaker
 */
public class Board extends javax.swing.JFrame {

	/**
	 * Creates new form Board1
	 */
	
	int [][] userVals;
	int [][] vals;
	
	Check[] checks;
	
	public Board() {
		initComponents();
		
		userVals = new int[9][9];
		vals = new int[9][9];
		checks = new Check[3];
		checks[0] = new CheckBox();
		checks[1] = new CheckHorizontal();
		checks[2] = new CheckVertical();
		
		genNewBoard();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                _4x1 = new javax.swing.JTextField();
                _5x1 = new javax.swing.JTextField();
                _4x3 = new javax.swing.JTextField();
                _5x3 = new javax.swing.JTextField();
                _6x5 = new javax.swing.JTextField();
                _6x3 = new javax.swing.JTextField();
                _7x3 = new javax.swing.JTextField();
                _7x5 = new javax.swing.JTextField();
                _8x3 = new javax.swing.JTextField();
                _9x3 = new javax.swing.JTextField();
                _8x5 = new javax.swing.JTextField();
                _1x3 = new javax.swing.JTextField();
                _6x1 = new javax.swing.JTextField();
                _2x3 = new javax.swing.JTextField();
                _7x1 = new javax.swing.JTextField();
                _3x3 = new javax.swing.JTextField();
                _8x1 = new javax.swing.JTextField();
                _9x1 = new javax.swing.JTextField();
                _9x5 = new javax.swing.JTextField();
                _1x5 = new javax.swing.JTextField();
                _4x6 = new javax.swing.JTextField();
                _5x6 = new javax.swing.JTextField();
                _6x6 = new javax.swing.JTextField();
                _7x6 = new javax.swing.JTextField();
                _8x6 = new javax.swing.JTextField();
                _9x6 = new javax.swing.JTextField();
                _6x8 = new javax.swing.JTextField();
                _1x1 = new javax.swing.JTextField();
                _1x6 = new javax.swing.JTextField();
                _7x8 = new javax.swing.JTextField();
                _2x6 = new javax.swing.JTextField();
                _8x8 = new javax.swing.JTextField();
                _9x8 = new javax.swing.JTextField();
                _1x8 = new javax.swing.JTextField();
                _4x9 = new javax.swing.JTextField();
                _5x9 = new javax.swing.JTextField();
                _6x9 = new javax.swing.JTextField();
                _7x9 = new javax.swing.JTextField();
                _8x9 = new javax.swing.JTextField();
                _3x6 = new javax.swing.JTextField();
                _2x5 = new javax.swing.JTextField();
                _3x5 = new javax.swing.JTextField();
                _9x9 = new javax.swing.JTextField();
                _1x9 = new javax.swing.JTextField();
                _2x9 = new javax.swing.JTextField();
                _3x9 = new javax.swing.JTextField();
                _4x4 = new javax.swing.JTextField();
                _2x8 = new javax.swing.JTextField();
                _5x4 = new javax.swing.JTextField();
                _3x8 = new javax.swing.JTextField();
                _6x4 = new javax.swing.JTextField();
                _4x7 = new javax.swing.JTextField();
                _5x7 = new javax.swing.JTextField();
                _6x7 = new javax.swing.JTextField();
                _7x7 = new javax.swing.JTextField();
                _7x4 = new javax.swing.JTextField();
                _8x4 = new javax.swing.JTextField();
                _9x4 = new javax.swing.JTextField();
                _1x4 = new javax.swing.JTextField();
                _8x7 = new javax.swing.JTextField();
                _2x4 = new javax.swing.JTextField();
                _9x7 = new javax.swing.JTextField();
                _4x2 = new javax.swing.JTextField();
                _3x4 = new javax.swing.JTextField();
                _1x7 = new javax.swing.JTextField();
                _5x2 = new javax.swing.JTextField();
                _4x5 = new javax.swing.JTextField();
                _2x7 = new javax.swing.JTextField();
                _6x2 = new javax.swing.JTextField();
                _5x5 = new javax.swing.JTextField();
                _3x7 = new javax.swing.JTextField();
                _7x2 = new javax.swing.JTextField();
                _4x8 = new javax.swing.JTextField();
                _8x2 = new javax.swing.JTextField();
                _5x8 = new javax.swing.JTextField();
                _9x2 = new javax.swing.JTextField();
                jButton1 = new javax.swing.JButton();
                _1x2 = new javax.swing.JTextField();
                _2x2 = new javax.swing.JTextField();
                _3x2 = new javax.swing.JTextField();
                _2x1 = new javax.swing.JTextField();
                _3x1 = new javax.swing.JTextField();
                jButton2 = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jButton1.setText("Finnished");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                jButton2.setText("New");
                jButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton2ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(_1x1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_2x1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_3x1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(_1x2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_2x2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_3x2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(_1x3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_2x3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_3x3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(_1x4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_2x4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_3x4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(_1x5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_2x5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_3x5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(_1x6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_2x6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_3x6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(_1x7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_2x7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_3x7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(_1x8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_2x8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_3x8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(_1x9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_2x9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_3x9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(_4x1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_5x1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_6x1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(_4x2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_5x2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_6x2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(_4x3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_5x3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_6x3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(_4x4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_5x4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_6x4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(_4x5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_5x5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_6x5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(_4x6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_5x6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_6x6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(_4x7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_5x7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_6x7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(_4x8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_5x8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_6x8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(_4x9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_5x9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_6x9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(20, 20, 20)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(_7x1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_8x1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_9x1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(_7x2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_8x2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_9x2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(_7x3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_8x3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_9x3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(_7x4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_8x4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_9x4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(_7x5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_8x5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_9x5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(_7x6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_8x6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_9x6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(_7x7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_8x7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_9x7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(_7x8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_8x8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_9x8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(_7x9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_8x9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(_9x9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(_1x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_2x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_3x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_4x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_5x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_6x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_7x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_8x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_9x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(_1x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_2x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_3x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_4x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_5x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_6x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_7x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_8x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_9x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(_1x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_2x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_3x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_4x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_5x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_6x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_7x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_8x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_9x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(_1x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_2x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_3x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_4x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_5x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_6x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_7x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_8x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_9x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(_1x5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_2x5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_3x5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_4x5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_5x5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_6x5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_7x5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_8x5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_9x5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(_1x6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_2x6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_3x6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_4x6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_5x6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_6x6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_7x6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_8x6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_9x6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(_1x7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_2x7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_3x7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_4x7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_5x7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_6x7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_7x7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_8x7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_9x7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(_1x8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_2x8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_3x8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_4x8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_5x8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_6x8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_7x8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_8x8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_9x8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(_1x9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_2x9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_3x9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_4x9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_5x9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_6x9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_7x9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_8x9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(_9x9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton1)
                                        .addComponent(jButton2))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

	

	
	private void resetAll()
	{
		_1x1.setText(" "); _1x1.setEditable(true); _1x1.setForeground(Color.black);
		_1x2.setText(" "); _1x2.setEditable(true); _1x2.setForeground(Color.black);
		_1x3.setText(" "); _1x3.setEditable(true); _1x3.setForeground(Color.black);
		_1x4.setText(" "); _1x4.setEditable(true); _1x4.setForeground(Color.black);
		_1x5.setText(" "); _1x5.setEditable(true); _1x5.setForeground(Color.black);
		_1x6.setText(" "); _1x6.setEditable(true); _1x6.setForeground(Color.black);
		_1x7.setText(" "); _1x7.setEditable(true); _1x7.setForeground(Color.black);
		_1x8.setText(" "); _1x8.setEditable(true); _1x8.setForeground(Color.black);
		_1x9.setText(" "); _1x9.setEditable(true); _1x9.setForeground(Color.black);
		_2x1.setText(" "); _2x1.setEditable(true); _2x1.setForeground(Color.black);
		_2x2.setText(" "); _2x2.setEditable(true); _2x2.setForeground(Color.black);
		_2x3.setText(" "); _2x3.setEditable(true); _2x3.setForeground(Color.black);
		_2x4.setText(" "); _2x4.setEditable(true); _2x4.setForeground(Color.black);
		_2x5.setText(" "); _2x5.setEditable(true); _2x5.setForeground(Color.black);
		_2x6.setText(" "); _2x6.setEditable(true); _2x6.setForeground(Color.black);
		_2x7.setText(" "); _2x7.setEditable(true); _2x7.setForeground(Color.black);
		_2x8.setText(" "); _2x8.setEditable(true); _2x8.setForeground(Color.black);
		_2x9.setText(" "); _2x9.setEditable(true); _2x9.setForeground(Color.black);
		_3x1.setText(" "); _3x1.setEditable(true); _3x1.setForeground(Color.black);
		_3x2.setText(" "); _3x2.setEditable(true); _3x2.setForeground(Color.black);
		_3x3.setText(" "); _3x3.setEditable(true); _3x3.setForeground(Color.black);
		_3x4.setText(" "); _3x4.setEditable(true); _3x4.setForeground(Color.black);
		_3x5.setText(" "); _3x5.setEditable(true); _3x5.setForeground(Color.black);
		_3x6.setText(" "); _3x6.setEditable(true); _3x6.setForeground(Color.black);
		_3x7.setText(" "); _3x7.setEditable(true); _3x7.setForeground(Color.black);
		_3x8.setText(" "); _3x8.setEditable(true); _3x8.setForeground(Color.black);
		_3x9.setText(" "); _3x9.setEditable(true); _3x9.setForeground(Color.black);
		_4x1.setText(" "); _4x1.setEditable(true); _4x1.setForeground(Color.black);
		_4x2.setText(" "); _4x2.setEditable(true); _4x2.setForeground(Color.black);
		_4x3.setText(" "); _4x3.setEditable(true); _4x3.setForeground(Color.black);
		_4x4.setText(" "); _4x4.setEditable(true); _4x4.setForeground(Color.black);
		_4x5.setText(" "); _4x5.setEditable(true); _4x5.setForeground(Color.black);
		_4x6.setText(" "); _4x6.setEditable(true); _4x6.setForeground(Color.black);
		_4x7.setText(" "); _4x7.setEditable(true); _4x7.setForeground(Color.black);
		_4x8.setText(" "); _4x8.setEditable(true); _4x8.setForeground(Color.black);
		_4x9.setText(" "); _4x9.setEditable(true); _4x9.setForeground(Color.black);
		_5x1.setText(" "); _5x1.setEditable(true); _5x1.setForeground(Color.black);
		_5x2.setText(" "); _5x2.setEditable(true); _5x2.setForeground(Color.black);
		_5x3.setText(" "); _5x3.setEditable(true); _5x3.setForeground(Color.black);
		_5x4.setText(" "); _5x4.setEditable(true); _5x4.setForeground(Color.black);
		_5x5.setText(" "); _5x5.setEditable(true); _5x5.setForeground(Color.black);
		_5x6.setText(" "); _5x6.setEditable(true); _5x6.setForeground(Color.black);
		_5x7.setText(" "); _5x7.setEditable(true); _5x7.setForeground(Color.black);
		_5x8.setText(" "); _5x8.setEditable(true); _5x8.setForeground(Color.black);
		_5x9.setText(" "); _5x9.setEditable(true); _5x9.setForeground(Color.black);
		_6x1.setText(" "); _6x1.setEditable(true); _6x1.setForeground(Color.black);
		_6x2.setText(" "); _6x2.setEditable(true); _6x2.setForeground(Color.black);
		_6x3.setText(" "); _6x3.setEditable(true); _6x3.setForeground(Color.black);
		_6x4.setText(" "); _6x4.setEditable(true); _6x4.setForeground(Color.black);
		_6x5.setText(" "); _6x5.setEditable(true); _6x5.setForeground(Color.black);
		_6x6.setText(" "); _6x6.setEditable(true); _6x6.setForeground(Color.black);
		_6x7.setText(" "); _6x7.setEditable(true); _6x7.setForeground(Color.black);
		_6x8.setText(" "); _6x8.setEditable(true); _6x8.setForeground(Color.black);
		_6x9.setText(" "); _6x9.setEditable(true); _6x9.setForeground(Color.black);
		_7x1.setText(" "); _7x1.setEditable(true); _7x1.setForeground(Color.black);
		_7x2.setText(" "); _7x2.setEditable(true); _7x2.setForeground(Color.black);
		_7x3.setText(" "); _7x3.setEditable(true); _7x3.setForeground(Color.black);
		_7x4.setText(" "); _7x4.setEditable(true); _7x4.setForeground(Color.black);
		_7x5.setText(" "); _7x5.setEditable(true); _7x5.setForeground(Color.black);
		_7x6.setText(" "); _7x6.setEditable(true); _7x6.setForeground(Color.black);
		_7x7.setText(" "); _7x7.setEditable(true); _7x7.setForeground(Color.black);
		_7x8.setText(" "); _7x8.setEditable(true); _7x8.setForeground(Color.black);
		_7x9.setText(" "); _7x9.setEditable(true); _7x9.setForeground(Color.black);
		_8x1.setText(" "); _8x1.setEditable(true); _8x1.setForeground(Color.black);
		_8x2.setText(" "); _8x2.setEditable(true); _8x2.setForeground(Color.black);
		_8x3.setText(" "); _8x3.setEditable(true); _8x3.setForeground(Color.black);
		_8x4.setText(" "); _8x4.setEditable(true); _8x4.setForeground(Color.black);
		_8x5.setText(" "); _8x5.setEditable(true); _8x5.setForeground(Color.black);
		_8x6.setText(" "); _8x6.setEditable(true); _8x6.setForeground(Color.black);
		_8x7.setText(" "); _8x7.setEditable(true); _8x7.setForeground(Color.black);
		_8x8.setText(" "); _8x8.setEditable(true); _8x8.setForeground(Color.black);
		_8x9.setText(" "); _8x9.setEditable(true); _8x9.setForeground(Color.black);
		_9x1.setText(" "); _9x1.setEditable(true); _9x1.setForeground(Color.black);
		_9x2.setText(" "); _9x2.setEditable(true); _9x2.setForeground(Color.black);
		_9x3.setText(" "); _9x3.setEditable(true); _9x3.setForeground(Color.black);
		_9x4.setText(" "); _9x4.setEditable(true); _9x4.setForeground(Color.black);
		_9x5.setText(" "); _9x5.setEditable(true); _9x5.setForeground(Color.black);
		_9x6.setText(" "); _9x6.setEditable(true); _9x6.setForeground(Color.black);
		_9x7.setText(" "); _9x7.setEditable(true); _9x7.setForeground(Color.black);
		_9x8.setText(" "); _9x8.setEditable(true); _9x8.setForeground(Color.black);
		_9x9.setText(" "); _9x9.setEditable(true); _9x9.setForeground(Color.black);
		
		userVals = new int[9][9];
		vals = new int[9][9];
	}
	
	
	//returns false when textfield is blank
	//
	private boolean readValsIn()
	{
		try{
		userVals[0][0] = Integer.parseInt(_1x1.getText().replaceAll("\\s+",""));
		userVals[1][0] = Integer.parseInt(_1x2.getText().replaceAll("\\s+",""));
		userVals[2][0] = Integer.parseInt(_1x3.getText().replaceAll("\\s+",""));
		userVals[3][0] = Integer.parseInt(_1x4.getText().replaceAll("\\s+",""));
		userVals[4][0] = Integer.parseInt(_1x5.getText().replaceAll("\\s+",""));
		userVals[5][0] = Integer.parseInt(_1x6.getText().replaceAll("\\s+",""));
		userVals[6][0] = Integer.parseInt(_1x7.getText().replaceAll("\\s+",""));
		userVals[7][0] = Integer.parseInt(_1x8.getText().replaceAll("\\s+",""));
		userVals[8][0] = Integer.parseInt(_1x9.getText().replaceAll("\\s+",""));
		userVals[0][1] = Integer.parseInt(_2x1.getText().replaceAll("\\s+",""));
		userVals[1][1] = Integer.parseInt(_2x2.getText().replaceAll("\\s+",""));
		userVals[2][1] = Integer.parseInt(_2x3.getText().replaceAll("\\s+",""));
		userVals[3][1] = Integer.parseInt(_2x4.getText().replaceAll("\\s+",""));
		userVals[4][1] = Integer.parseInt(_2x5.getText().replaceAll("\\s+",""));
		userVals[5][1] = Integer.parseInt(_2x6.getText().replaceAll("\\s+",""));
		userVals[6][1] = Integer.parseInt(_2x7.getText().replaceAll("\\s+",""));
		userVals[7][1] = Integer.parseInt(_2x8.getText().replaceAll("\\s+",""));
		userVals[8][1] = Integer.parseInt(_2x9.getText().replaceAll("\\s+",""));
		userVals[0][2] = Integer.parseInt(_3x1.getText().replaceAll("\\s+",""));
		userVals[1][2] = Integer.parseInt(_3x2.getText().replaceAll("\\s+",""));
		userVals[2][2] = Integer.parseInt(_3x3.getText().replaceAll("\\s+",""));
		userVals[3][2] = Integer.parseInt(_3x4.getText().replaceAll("\\s+",""));
		userVals[4][2] = Integer.parseInt(_3x5.getText().replaceAll("\\s+",""));
		userVals[5][2] = Integer.parseInt(_3x6.getText().replaceAll("\\s+",""));
		userVals[6][2] = Integer.parseInt(_3x7.getText().replaceAll("\\s+",""));
		userVals[7][2] = Integer.parseInt(_3x8.getText().replaceAll("\\s+",""));
		userVals[8][2] = Integer.parseInt(_3x9.getText().replaceAll("\\s+",""));
		userVals[0][3] = Integer.parseInt(_4x1.getText().replaceAll("\\s+",""));
		userVals[1][3] = Integer.parseInt(_4x2.getText().replaceAll("\\s+",""));
		userVals[2][3] = Integer.parseInt(_4x3.getText().replaceAll("\\s+",""));
		userVals[3][3] = Integer.parseInt(_4x4.getText().replaceAll("\\s+",""));
		userVals[4][3] = Integer.parseInt(_4x5.getText().replaceAll("\\s+",""));
		userVals[5][3] = Integer.parseInt(_4x6.getText().replaceAll("\\s+",""));
		userVals[6][3] = Integer.parseInt(_4x7.getText().replaceAll("\\s+",""));
		userVals[7][3] = Integer.parseInt(_4x8.getText().replaceAll("\\s+",""));
		userVals[8][3] = Integer.parseInt(_4x9.getText().replaceAll("\\s+",""));
		userVals[0][4] = Integer.parseInt(_5x1.getText().replaceAll("\\s+",""));
		userVals[1][4] = Integer.parseInt(_5x2.getText().replaceAll("\\s+",""));
		userVals[2][4] = Integer.parseInt(_5x3.getText().replaceAll("\\s+",""));
		userVals[3][4] = Integer.parseInt(_5x4.getText().replaceAll("\\s+",""));
		userVals[4][4] = Integer.parseInt(_5x5.getText().replaceAll("\\s+",""));
		userVals[5][4] = Integer.parseInt(_5x6.getText().replaceAll("\\s+",""));
		userVals[6][4] = Integer.parseInt(_5x7.getText().replaceAll("\\s+",""));
		userVals[7][4] = Integer.parseInt(_5x8.getText().replaceAll("\\s+",""));
		userVals[8][4] = Integer.parseInt(_5x9.getText().replaceAll("\\s+",""));
		userVals[0][5] = Integer.parseInt(_6x1.getText().replaceAll("\\s+",""));
		userVals[1][5] = Integer.parseInt(_6x2.getText().replaceAll("\\s+",""));
		userVals[2][5] = Integer.parseInt(_6x3.getText().replaceAll("\\s+",""));
		userVals[3][5] = Integer.parseInt(_6x4.getText().replaceAll("\\s+",""));
		userVals[4][5] = Integer.parseInt(_6x5.getText().replaceAll("\\s+",""));
		userVals[5][5] = Integer.parseInt(_6x6.getText().replaceAll("\\s+",""));
		userVals[6][5] = Integer.parseInt(_6x7.getText().replaceAll("\\s+",""));
		userVals[7][5] = Integer.parseInt(_6x8.getText().replaceAll("\\s+",""));
		userVals[8][5] = Integer.parseInt(_6x9.getText().replaceAll("\\s+",""));
		userVals[0][6] = Integer.parseInt(_7x1.getText().replaceAll("\\s+",""));
		userVals[1][6] = Integer.parseInt(_7x2.getText().replaceAll("\\s+",""));
		userVals[2][6] = Integer.parseInt(_7x3.getText().replaceAll("\\s+",""));
		userVals[3][6] = Integer.parseInt(_7x4.getText().replaceAll("\\s+",""));
		userVals[4][6] = Integer.parseInt(_7x5.getText().replaceAll("\\s+",""));
		userVals[5][6] = Integer.parseInt(_7x6.getText().replaceAll("\\s+",""));
		userVals[6][6] = Integer.parseInt(_7x7.getText().replaceAll("\\s+",""));
		userVals[7][6] = Integer.parseInt(_7x8.getText().replaceAll("\\s+",""));
		userVals[8][6] = Integer.parseInt(_7x9.getText().replaceAll("\\s+",""));
		userVals[0][7] = Integer.parseInt(_8x1.getText().replaceAll("\\s+",""));
		userVals[1][7] = Integer.parseInt(_8x2.getText().replaceAll("\\s+",""));
		userVals[2][7] = Integer.parseInt(_8x3.getText().replaceAll("\\s+",""));
		userVals[3][7] = Integer.parseInt(_8x4.getText().replaceAll("\\s+",""));
		userVals[4][7] = Integer.parseInt(_8x5.getText().replaceAll("\\s+",""));
		userVals[5][7] = Integer.parseInt(_8x6.getText().replaceAll("\\s+",""));
		userVals[6][7] = Integer.parseInt(_8x7.getText().replaceAll("\\s+",""));
		userVals[7][7] = Integer.parseInt(_8x8.getText().replaceAll("\\s+",""));
		userVals[8][7] = Integer.parseInt(_8x9.getText().replaceAll("\\s+",""));
		userVals[0][8] = Integer.parseInt(_9x1.getText().replaceAll("\\s+",""));
		userVals[1][8] = Integer.parseInt(_9x2.getText().replaceAll("\\s+",""));
		userVals[2][8] = Integer.parseInt(_9x3.getText().replaceAll("\\s+",""));
		userVals[3][8] = Integer.parseInt(_9x4.getText().replaceAll("\\s+",""));
		userVals[4][8] = Integer.parseInt(_9x5.getText().replaceAll("\\s+",""));
		userVals[5][8] = Integer.parseInt(_9x6.getText().replaceAll("\\s+",""));
		userVals[6][8] = Integer.parseInt(_9x7.getText().replaceAll("\\s+",""));
		userVals[7][8] = Integer.parseInt(_9x8.getText().replaceAll("\\s+",""));
		userVals[8][8] = Integer.parseInt(_9x9.getText().replaceAll("\\s+",""));
	}
	catch(Exception ex)
	{
		return false;
	}	
	return true;
	}
	
	
	//Sets text box at x,y to readOnly, colour to red and the text to the given value 
	public void setValBoard(int x, int y)
	{
		if(x == 1 && y == 1){_1x1.setText(String.valueOf(vals[0][0])); _1x1.setEditable(false); _1x1.setForeground(Color.red); } 
		else if(x == 1 && y == 2){_1x2.setText(String.valueOf(vals[1][0])); _1x2.setEditable(false); _1x2.setForeground(Color.red); } 
		else if(x == 1 && y == 3){_1x3.setText(String.valueOf(vals[2][0])); _1x3.setEditable(false); _1x3.setForeground(Color.red); } 
		else if(x == 1 && y == 4){_1x4.setText(String.valueOf(vals[3][0])); _1x4.setEditable(false); _1x4.setForeground(Color.red); } 
		else if(x == 1 && y == 5){_1x5.setText(String.valueOf(vals[4][0])); _1x5.setEditable(false); _1x5.setForeground(Color.red); } 
		else if(x == 1 && y == 6){_1x6.setText(String.valueOf(vals[5][0])); _1x6.setEditable(false); _1x6.setForeground(Color.red); } 
		else if(x == 1 && y == 7){_1x7.setText(String.valueOf(vals[6][0])); _1x7.setEditable(false); _1x7.setForeground(Color.red); } 
		else if(x == 1 && y == 8){_1x8.setText(String.valueOf(vals[7][0])); _1x8.setEditable(false); _1x8.setForeground(Color.red); } 
		else if(x == 1 && y == 9){_1x9.setText(String.valueOf(vals[8][0])); _1x9.setEditable(false); _1x9.setForeground(Color.red); } 
		else if(x == 2 && y == 1){_2x1.setText(String.valueOf(vals[0][1])); _2x1.setEditable(false); _2x1.setForeground(Color.red); } 
		else if(x == 2 && y == 2){_2x2.setText(String.valueOf(vals[1][1])); _2x2.setEditable(false); _2x2.setForeground(Color.red); } 
		else if(x == 2 && y == 3){_2x3.setText(String.valueOf(vals[2][1])); _2x3.setEditable(false); _2x3.setForeground(Color.red); } 
		else if(x == 2 && y == 4){_2x4.setText(String.valueOf(vals[3][1])); _2x4.setEditable(false); _2x4.setForeground(Color.red); } 
		else if(x == 2 && y == 5){_2x5.setText(String.valueOf(vals[4][1])); _2x5.setEditable(false); _2x5.setForeground(Color.red); } 
		else if(x == 2 && y == 6){_2x6.setText(String.valueOf(vals[5][1])); _2x6.setEditable(false); _2x6.setForeground(Color.red); } 
		else if(x == 2 && y == 7){_2x7.setText(String.valueOf(vals[6][1])); _2x7.setEditable(false); _2x7.setForeground(Color.red); } 
		else if(x == 2 && y == 8){_2x8.setText(String.valueOf(vals[7][1])); _2x8.setEditable(false); _2x8.setForeground(Color.red); } 
		else if(x == 2 && y == 9){_2x9.setText(String.valueOf(vals[8][1])); _2x9.setEditable(false); _2x9.setForeground(Color.red); } 
		else if(x == 3 && y == 1){_3x1.setText(String.valueOf(vals[0][2])); _3x1.setEditable(false); _3x1.setForeground(Color.red); } 
		else if(x == 3 && y == 2){_3x2.setText(String.valueOf(vals[1][2])); _3x2.setEditable(false); _3x2.setForeground(Color.red); } 
		else if(x == 3 && y == 3){_3x3.setText(String.valueOf(vals[2][2])); _3x3.setEditable(false); _3x3.setForeground(Color.red); } 
		else if(x == 3 && y == 4){_3x4.setText(String.valueOf(vals[3][2])); _3x4.setEditable(false); _3x4.setForeground(Color.red); } 
		else if(x == 3 && y == 5){_3x5.setText(String.valueOf(vals[4][2])); _3x5.setEditable(false); _3x5.setForeground(Color.red); } 
		else if(x == 3 && y == 6){_3x6.setText(String.valueOf(vals[5][2])); _3x6.setEditable(false); _3x6.setForeground(Color.red); } 
		else if(x == 3 && y == 7){_3x7.setText(String.valueOf(vals[6][2])); _3x7.setEditable(false); _3x7.setForeground(Color.red); } 
		else if(x == 3 && y == 8){_3x8.setText(String.valueOf(vals[7][2])); _3x8.setEditable(false); _3x8.setForeground(Color.red); } 
		else if(x == 3 && y == 9){_3x9.setText(String.valueOf(vals[8][2])); _3x9.setEditable(false); _3x9.setForeground(Color.red); } 
		else if(x == 4 && y == 1){_4x1.setText(String.valueOf(vals[0][3])); _4x1.setEditable(false); _4x1.setForeground(Color.red); } 
		else if(x == 4 && y == 2){_4x2.setText(String.valueOf(vals[1][3])); _4x2.setEditable(false); _4x2.setForeground(Color.red); } 
		else if(x == 4 && y == 3){_4x3.setText(String.valueOf(vals[2][3])); _4x3.setEditable(false); _4x3.setForeground(Color.red); } 
		else if(x == 4 && y == 4){_4x4.setText(String.valueOf(vals[3][3])); _4x4.setEditable(false); _4x4.setForeground(Color.red); } 
		else if(x == 4 && y == 5){_4x5.setText(String.valueOf(vals[4][3])); _4x5.setEditable(false); _4x5.setForeground(Color.red); } 
		else if(x == 4 && y == 6){_4x6.setText(String.valueOf(vals[5][3])); _4x6.setEditable(false); _4x6.setForeground(Color.red); } 
		else if(x == 4 && y == 7){_4x7.setText(String.valueOf(vals[6][3])); _4x7.setEditable(false); _4x7.setForeground(Color.red); } 
		else if(x == 4 && y == 8){_4x8.setText(String.valueOf(vals[7][3])); _4x8.setEditable(false); _4x8.setForeground(Color.red); } 
		else if(x == 4 && y == 9){_4x9.setText(String.valueOf(vals[8][3])); _4x9.setEditable(false); _4x9.setForeground(Color.red); } 
		else if(x == 5 && y == 1){_5x1.setText(String.valueOf(vals[0][4])); _5x1.setEditable(false); _5x1.setForeground(Color.red); } 
		else if(x == 5 && y == 2){_5x2.setText(String.valueOf(vals[1][4])); _5x2.setEditable(false); _5x2.setForeground(Color.red); } 
		else if(x == 5 && y == 3){_5x3.setText(String.valueOf(vals[2][4])); _5x3.setEditable(false); _5x3.setForeground(Color.red); } 
		else if(x == 5 && y == 4){_5x4.setText(String.valueOf(vals[3][4])); _5x4.setEditable(false); _5x4.setForeground(Color.red); } 
		else if(x == 5 && y == 5){_5x5.setText(String.valueOf(vals[4][4])); _5x5.setEditable(false); _5x5.setForeground(Color.red); } 
		else if(x == 5 && y == 6){_5x6.setText(String.valueOf(vals[5][4])); _5x6.setEditable(false); _5x6.setForeground(Color.red); } 
		else if(x == 5 && y == 7){_5x7.setText(String.valueOf(vals[6][4])); _5x7.setEditable(false); _5x7.setForeground(Color.red); } 
		else if(x == 5 && y == 8){_5x8.setText(String.valueOf(vals[7][4])); _5x8.setEditable(false); _5x8.setForeground(Color.red); } 
		else if(x == 5 && y == 9){_5x9.setText(String.valueOf(vals[8][4])); _5x9.setEditable(false); _5x9.setForeground(Color.red); } 
		else if(x == 6 && y == 1){_6x1.setText(String.valueOf(vals[0][5])); _6x1.setEditable(false); _6x1.setForeground(Color.red); } 
		else if(x == 6 && y == 2){_6x2.setText(String.valueOf(vals[1][5])); _6x2.setEditable(false); _6x2.setForeground(Color.red); } 
		else if(x == 6 && y == 3){_6x3.setText(String.valueOf(vals[2][5])); _6x3.setEditable(false); _6x3.setForeground(Color.red); } 
		else if(x == 6 && y == 4){_6x4.setText(String.valueOf(vals[3][5])); _6x4.setEditable(false); _6x4.setForeground(Color.red); } 
		else if(x == 6 && y == 5){_6x5.setText(String.valueOf(vals[4][5])); _6x5.setEditable(false); _6x5.setForeground(Color.red); } 
		else if(x == 6 && y == 6){_6x6.setText(String.valueOf(vals[5][5])); _6x6.setEditable(false); _6x6.setForeground(Color.red); } 
		else if(x == 6 && y == 7){_6x7.setText(String.valueOf(vals[6][5])); _6x7.setEditable(false); _6x7.setForeground(Color.red); } 
		else if(x == 6 && y == 8){_6x8.setText(String.valueOf(vals[7][5])); _6x8.setEditable(false); _6x8.setForeground(Color.red); } 
		else if(x == 6 && y == 9){_6x9.setText(String.valueOf(vals[8][5])); _6x9.setEditable(false); _6x9.setForeground(Color.red); } 
		else if(x == 7 && y == 1){_7x1.setText(String.valueOf(vals[0][6])); _7x1.setEditable(false); _7x1.setForeground(Color.red); } 
		else if(x == 7 && y == 2){_7x2.setText(String.valueOf(vals[1][6])); _7x2.setEditable(false); _7x2.setForeground(Color.red); } 
		else if(x == 7 && y == 3){_7x3.setText(String.valueOf(vals[2][6])); _7x3.setEditable(false); _7x3.setForeground(Color.red); } 
		else if(x == 7 && y == 4){_7x4.setText(String.valueOf(vals[3][6])); _7x4.setEditable(false); _7x4.setForeground(Color.red); } 
		else if(x == 7 && y == 5){_7x5.setText(String.valueOf(vals[4][6])); _7x5.setEditable(false); _7x5.setForeground(Color.red); } 
		else if(x == 7 && y == 6){_7x6.setText(String.valueOf(vals[5][6])); _7x6.setEditable(false); _7x6.setForeground(Color.red); } 
		else if(x == 7 && y == 7){_7x7.setText(String.valueOf(vals[6][6])); _7x7.setEditable(false); _7x7.setForeground(Color.red); } 
		else if(x == 7 && y == 8){_7x8.setText(String.valueOf(vals[7][6])); _7x8.setEditable(false); _7x8.setForeground(Color.red); } 
		else if(x == 7 && y == 9){_7x9.setText(String.valueOf(vals[8][6])); _7x9.setEditable(false); _7x9.setForeground(Color.red); } 
		else if(x == 8 && y == 1){_8x1.setText(String.valueOf(vals[0][7])); _8x1.setEditable(false); _8x1.setForeground(Color.red); } 
		else if(x == 8 && y == 2){_8x2.setText(String.valueOf(vals[1][7])); _8x2.setEditable(false); _8x2.setForeground(Color.red); } 
		else if(x == 8 && y == 3){_8x3.setText(String.valueOf(vals[2][7])); _8x3.setEditable(false); _8x3.setForeground(Color.red); } 
		else if(x == 8 && y == 4){_8x4.setText(String.valueOf(vals[3][7])); _8x4.setEditable(false); _8x4.setForeground(Color.red); } 
		else if(x == 8 && y == 5){_8x5.setText(String.valueOf(vals[4][7])); _8x5.setEditable(false); _8x5.setForeground(Color.red); } 
		else if(x == 8 && y == 6){_8x6.setText(String.valueOf(vals[5][7])); _8x6.setEditable(false); _8x6.setForeground(Color.red); } 
		else if(x == 8 && y == 7){_8x7.setText(String.valueOf(vals[6][7])); _8x7.setEditable(false); _8x7.setForeground(Color.red); } 
		else if(x == 8 && y == 8){_8x8.setText(String.valueOf(vals[7][7])); _8x8.setEditable(false); _8x8.setForeground(Color.red); } 
		else if(x == 8 && y == 9){_8x9.setText(String.valueOf(vals[8][7])); _8x9.setEditable(false); _8x9.setForeground(Color.red); } 
		else if(x == 9 && y == 1){_9x1.setText(String.valueOf(vals[0][8])); _9x1.setEditable(false); _9x1.setForeground(Color.red); } 
		else if(x == 9 && y == 2){_9x2.setText(String.valueOf(vals[1][8])); _9x2.setEditable(false); _9x2.setForeground(Color.red); } 
		else if(x == 9 && y == 3){_9x3.setText(String.valueOf(vals[2][8])); _9x3.setEditable(false); _9x3.setForeground(Color.red); } 
		else if(x == 9 && y == 4){_9x4.setText(String.valueOf(vals[3][8])); _9x4.setEditable(false); _9x4.setForeground(Color.red); } 
		else if(x == 9 && y == 5){_9x5.setText(String.valueOf(vals[4][8])); _9x5.setEditable(false); _9x5.setForeground(Color.red); } 
		else if(x == 9 && y == 6){_9x6.setText(String.valueOf(vals[5][8])); _9x6.setEditable(false); _9x6.setForeground(Color.red); } 
		else if(x == 9 && y == 7){_9x7.setText(String.valueOf(vals[6][8])); _9x7.setEditable(false); _9x7.setForeground(Color.red); } 
		else if(x == 9 && y == 8){_9x8.setText(String.valueOf(vals[7][8])); _9x8.setEditable(false); _9x8.setForeground(Color.red); } 
		else if(x == 9 && y == 9){_9x9.setText(String.valueOf(vals[8][8])); _9x9.setEditable(false); _9x9.setForeground(Color.red); } 
		
	}
	
	private boolean performChecks()
	{
		boolean out = true;
		for(Check i : checks)
			if(!i.checkMoves(userVals))
				out = false;
		return out;
	}
	
	
	private void genNewBoard()
	{
		resetAll();
		try
		{
			vals = PuzzleGenerator.generate();
		}
		catch(Exception ex)
		{
			
		}
		
		
		//chose shown coords		
			
		for(int x = 0; x < 9; x++)
		{
			for(int y = 0; y < 9; y++)
			{
				if(vals[y][x] != 0)
					setValBoard(x+1, y+1);
			}
		}
		
	}
	
	
        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

		if(readValsIn())
		{
			//board is filled out
			if(performChecks())
				JOptionPane.showMessageDialog(null,"YOU WIN!!");
			else
				JOptionPane.showMessageDialog(null,"NOT CORRECT!!");
		}
		else
		{
			//board not filled return error
			JOptionPane.showMessageDialog(null,"BOARD NOT FINISHED!");
		}
        }//GEN-LAST:event_jButton1ActionPerformed

        private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
		genNewBoard();
        }//GEN-LAST:event_jButton2ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Board().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JTextField _1x1;
        private javax.swing.JTextField _1x2;
        private javax.swing.JTextField _1x3;
        private javax.swing.JTextField _1x4;
        private javax.swing.JTextField _1x5;
        private javax.swing.JTextField _1x6;
        private javax.swing.JTextField _1x7;
        private javax.swing.JTextField _1x8;
        private javax.swing.JTextField _1x9;
        private javax.swing.JTextField _2x1;
        private javax.swing.JTextField _2x2;
        private javax.swing.JTextField _2x3;
        private javax.swing.JTextField _2x4;
        private javax.swing.JTextField _2x5;
        private javax.swing.JTextField _2x6;
        private javax.swing.JTextField _2x7;
        private javax.swing.JTextField _2x8;
        private javax.swing.JTextField _2x9;
        private javax.swing.JTextField _3x1;
        private javax.swing.JTextField _3x2;
        private javax.swing.JTextField _3x3;
        private javax.swing.JTextField _3x4;
        private javax.swing.JTextField _3x5;
        private javax.swing.JTextField _3x6;
        private javax.swing.JTextField _3x7;
        private javax.swing.JTextField _3x8;
        private javax.swing.JTextField _3x9;
        private javax.swing.JTextField _4x1;
        private javax.swing.JTextField _4x2;
        private javax.swing.JTextField _4x3;
        private javax.swing.JTextField _4x4;
        private javax.swing.JTextField _4x5;
        private javax.swing.JTextField _4x6;
        private javax.swing.JTextField _4x7;
        private javax.swing.JTextField _4x8;
        private javax.swing.JTextField _4x9;
        private javax.swing.JTextField _5x1;
        private javax.swing.JTextField _5x2;
        private javax.swing.JTextField _5x3;
        private javax.swing.JTextField _5x4;
        private javax.swing.JTextField _5x5;
        private javax.swing.JTextField _5x6;
        private javax.swing.JTextField _5x7;
        private javax.swing.JTextField _5x8;
        private javax.swing.JTextField _5x9;
        private javax.swing.JTextField _6x1;
        private javax.swing.JTextField _6x2;
        private javax.swing.JTextField _6x3;
        private javax.swing.JTextField _6x4;
        private javax.swing.JTextField _6x5;
        private javax.swing.JTextField _6x6;
        private javax.swing.JTextField _6x7;
        private javax.swing.JTextField _6x8;
        private javax.swing.JTextField _6x9;
        private javax.swing.JTextField _7x1;
        private javax.swing.JTextField _7x2;
        private javax.swing.JTextField _7x3;
        private javax.swing.JTextField _7x4;
        private javax.swing.JTextField _7x5;
        private javax.swing.JTextField _7x6;
        private javax.swing.JTextField _7x7;
        private javax.swing.JTextField _7x8;
        private javax.swing.JTextField _7x9;
        private javax.swing.JTextField _8x1;
        private javax.swing.JTextField _8x2;
        private javax.swing.JTextField _8x3;
        private javax.swing.JTextField _8x4;
        private javax.swing.JTextField _8x5;
        private javax.swing.JTextField _8x6;
        private javax.swing.JTextField _8x7;
        private javax.swing.JTextField _8x8;
        private javax.swing.JTextField _8x9;
        private javax.swing.JTextField _9x1;
        private javax.swing.JTextField _9x2;
        private javax.swing.JTextField _9x3;
        private javax.swing.JTextField _9x4;
        private javax.swing.JTextField _9x5;
        private javax.swing.JTextField _9x6;
        private javax.swing.JTextField _9x7;
        private javax.swing.JTextField _9x8;
        private javax.swing.JTextField _9x9;
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        // End of variables declaration//GEN-END:variables
}
